### PR TITLE
Improve qmc.halton perf

### PR DESCRIPTION
**Pull request by V0lantis**

### CODE REVIEW

**Comment by V0lantis** [comment]
Hello @jb-leger and @rgommers. I would like to improve the function `van_der_corput` which is used in [`scipy.stats.qmc.hatlon`](https://github.com/scipy/scipy/blob/master/scipy/stats/_qmc.py#L504) class, in the random method.
This function uses random method which are declared in `numpy.random`. I have found their Cython implementations ([PCG64](https://github.com/numpy/numpy/blob/main/numpy/random/_pcg64.pyx)). This function import [`BitGenerator`](https://github.com/numpy/numpy/blob/79086a575643fe2505edaa444d2b800ec23f62ed/numpy/random/_pcg64.pyx#L6), which has also been declared in an other cython file. But when I try to import PCG64 as plain cython, doing `from numpy Cimport PCG64`, my compiler gives me an error. This is in order to have less interaction with the python GIL, to test if it is more performant. 

Do you have any idea how to manage this or how to improve it ?
Here is the generated file https://v0lantis.github.io/ImprovingHalton/

**Comment by jb-leger** [comment]
What error do you have?

For me, `PCG64` is not defined in any `pxd` files (e.g. `BitGenerator` is defined in [`__init__.pxd`](https://github.com/numpy/numpy/blob/main/numpy/random/__init__.pxd)), and should be not importable with `cimport`.

**Comment by V0lantis** [comment]
> What error do you have?
> 
> For me, `PCG64` is not defined in any `pxd` files (e.g. `BitGenerator` is defined in [`__init__.pxd`](https://github.com/numpy/numpy/blob/main/numpy/random/__init__.pxd)), and should be not importable with `cimport`.

Ok I think that's why I couldn't import it indeed. I would like to `import` PCG64 in order to have compiled code, but I don't know if it is possible. Because right now, I have a lot of dealing with Python Interpreter in my code ( https://v0lantis.github.io/ImprovingHalton/)

**Comment by rgommers** [comment]
The two examples at https://github.com/numpy/numpy/tree/main/numpy/random/_examples/cython use `PCG64`. 

> Because right now, I have a lot of dealing with Python Interpreter in my code ( https://v0lantis.github.io/ImprovingHalton/)

I'm not sure that would be faster with pure Cython code & memoryviews. The `permutation` and `shuffle` code in `numpy/random/_generator.pyx` is optimal for 1-D ndarrays. With numpy >= 1.20.2 (I believe that's the right bugfix release) memoryviews may be as fast. The `cdef` statements are not relevant for performance, and the creation of `perm` should be fine. So the only line of interest is:
```
remainder[i] = perm[int(remainder[i])]
```
I'm not sure why you declare all arrays as `double` and then do the `int` cast - can't they be `int32` or `int64` to begin with?

**Comment by V0lantis** [comment]
> The two examples at https://github.com/numpy/numpy/tree/main/numpy/random/_examples/cython use `PCG64`.
> 
> > Because right now, I have a lot of dealing with Python Interpreter in my code ( https://v0lantis.github.io/ImprovingHalton/)
> 
> I'm not sure that would be faster with pure Cython code & memoryviews. The `permutation` and `shuffle` code in `numpy/random/_generator.pyx` is optimal for 1-D ndarrays. With numpy >= 1.20.2 (I believe that's the right bugfix release) memoryviews may be as fast. The `cdef` statements are not relevant for performance, and the creation of `perm` should be fine. So the only line of interest is:
> 
> ```
> remainder[i] = perm[int(remainder[i])]
> ```
> 

Thank you for this review @rgommers ! I am going to try this out

> I'm not sure why you declare all arrays as `double` and then do the `int` cast - can't they be `int32` or `int64` to begin with?

Yes, I will try this out. Pamphile's request for Halton was mainly to be able to parallelize the function on multiple thread as I did with the discrepancy, but I would be glad to just optimize it at first

**Pull request closed without merging**
